config/routes.rb
Rails.application.routes.draw do
  resources :projects

  resources :bids

  resources :project_files

  resources :activity_logs

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/project_file.rb
class ProjectFile < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :activity_logs
end

app/controllers/project_files_controller.rb
class ProjectFilesController < ApplicationController
  before_action :set_project_file, only: [:show, :edit, :update, :destroy]

  # GET /project_files
  # GET /project_files.json
  def index
    @project_files = ProjectFile.all
  end

  # GET /project_files/1
  # GET /project_files/1.json
  def show
  end

  # GET /project_files/new
  def new
    @project_file = ProjectFile.new
  end

  # GET /project_files/1/edit
  def edit
  end

  # POST /project_files
  # POST /project_files.json
  def create
    @project_file = ProjectFile.new(project_file_params)

    respond_to do |format|
      if @project_file.save
        format.html { redirect_to @project_file, notice: 'Project file was successfully created.' }
        format.json { render :show, status: :created, location: @project_file }
      else
        format.html { render :new }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_files/1
  # PATCH/PUT /project_files/1.json
  def update
    respond_to do |format|
      if @project_file.update(project_file_params)
        format.html { redirect_to @project_file, notice: 'Project file was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_file }
      else
        format.html { render :edit }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_files/1
  # DELETE /project_files/1.json
  def destroy
    @project_file.destroy
    respond_to do |format|
      format.html { redirect_to project_files_url, notice: 'Project file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_file
      @project_file = ProjectFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_file_params
      params.require(:project_file).permit(:name, :folder, :project_id, :user_id)
    end
end

app/helpers/project_files_helper.rb
module ProjectFilesHelper
end

app/views/project_files/_form.html.erb
<%= form_for @project_file, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :folder, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :folder, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  project_files_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/project_files/edit.html.erb
<%- model_class = ProjectFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ProjectFile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/project_files/index.html.erb
<%- model_class = ProjectFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProjectFile %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:folder) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @project_files.each do |project_file| %>
      <tr>
        <td><%= project_file.id %></td>
        <td><%= project_file.name %></td>
        <td><%= project_file.folder %></td>
        <td><%=l project_file.created_at, format: :long %></td>
        <td>
          <%= link_to project_file_path(project_file), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to project_file_path(project_file), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_file_path,
            :class => 'btn btn-primary' %>

app/views/project_files/new.html.erb
<%- model_class = ProjectFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ProjectFile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/project_files/show.html.erb
<%- model_class = ProjectFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProjectFile %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @project_file.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:folder) %></dt>
      <dd><pre class="prettyprint"><%= @project_file.folder %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              project_files_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_file_path(@project_file), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_file_path(@project_file),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>